name: AutoRestart
main: net.azisaba.autorestart.AutoRestart
version: 1.1.0
author: pino223
api-version: 1.16
commands:
  autorestart:
    description: AutoRestart 設定リロードコマンド
    usage: /autorestart reload
    permission: autorestart.reload
permissions:
  autorestart.reload:
    description: AutoRestart設定をリロードする権限
    default: op
